export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const CUSTOMERS_ID = process.env.NEXT_PUBLIC_APPWRITE_CUSTOMERS_ID!;
export const STAFF_ID = process.env.NEXT_PUBLIC_APPWRITE_STAFF_ID!;
export const ROLES_ID = process.env.NEXT_PUBLIC_APPWRITE_ROLES_ID!;
export const STAFF_IMAGES_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_STAFF_IMAGES_BUCKET_ID!;
