export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const CUSTOMERS_ID = process.env.NEXT_PUBLIC_APPWRITE_CUSTOMERS_ID!;
export const STAFF_ID = process.env.NEXT_PUBLIC_APPWRITE_STAFF_ID!;
export const ROLES_ID = process.env.NEXT_PUBLIC_APPWRITE_ROLES_ID!;
export const STAFF_IMAGES_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_STAFF_IMAGES_BUCKET_ID!;
export const COUNTRIES_ID = process.env.NEXT_PUBLIC_APPWRITE_COUNTRIES_ID!;
export const CONVERTER_KEY = process.env.NEXT_PUBLIC_CURRENCY_CONVERTER_KEY!;
export const CONVERTER_BASE_URL =
  process.env.NEXT_PUBLIC_EXCHANGE_RATE_BASE_URL!;
export const EXCHANGE_RATES_ID = process.env.NEXT_PUBLIC_EXCHANGE_RATES_ID!;
export const RECIPIENTS_ID = process.env.NEXT_PUBLIC_RECIPIENTS_ID!;
export const TRANSFERS_ID = process.env.NEXT_PUBLIC_TRANSFERS_ID!;
export const FEES_AND_PROMOTIONS_ID =
  process.env.NEXT_PUBLIC_FEES_AND_PROMOTIONS_ID!;
